name: "Build base image"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    paths:
      - "Dockerfile.base"
      - ".github/workflows/base-image.yml"
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version (major.minor)'
        required: false
        type: string
      pydantic_version:
        description: 'Pydantic version'
        required: false
        type: string

jobs:
  build:
    name: "Build base image"
    runs-on: "ubuntu-latest"

    env:
      PYTHON_VERSION: ${{ inputs.python_version || '3.12' }}
      PYDANTIC_VERSION: ${{ inputs.pydantic_version || '2.7.4' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log versions
        run: |
          echo "Python: ${{ env.PYTHON_VERSION }}"
          echo "Pydantic : ${{ env.PYDANTIC_VERSION }}"

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ghcr.io/nuvlaedge/ne-base:python${{ env.PYTHON_VERSION }}-pydantic${{ env.PYDANTIC_VERSION }}
          build-args: |
            PYTHON_MAJ_MIN_VERSION=${{ env.PYTHON_VERSION }}
            PYDANTIC_VERSION=${{ env.PYDANTIC_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
